name: dwds
version: 0.1.0
description: >-
  A service that proxies between the Chrome debug protocol and the vm
  service protocol.
environment:
  sdk: ^2.1.0
dependencies:
  json_annotation: ^2.0.0
dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
